### ISSUE TITLE
auto-publish all commits?

### ISSUE THREAD

**Issue by dsilvasc** [scala/sbt-scala-module#93]
Hi,

Rather than manually publishing to a maven repository (there's an open [issue](https://github.com/scala/scala-async/issues/201) asking for 0.10 for a while now), would it be possible to auto-publish on every commit?  The version for automatically published artifacts could follow a different scheme like `0.0.$date.$commit` or `0.0.$(git rev-list HEAD --count)` if you also want to continue having manual releases.

**Comment by SethTisue** [comment]
transferred this issue from the scala-async repo where it was originally raised, since if we were to do this, I think we would want to handle it consistently for all the modules

the latest sbt-scala-module version brings in sbt-ci-release and sbt-dynver, so that helps

now that we're on sbt-ci-release, perhaps the need for this has lessened. we can publish (except for one manual step, see below) simply by pushing a tag — which is so easy it's not clear that further automation buys much

historically we don't do fully automated publishing for any of the modules. most modules are community maintained, but we (the Scala 2 team at Lightbend) retain a final gatekeeping role, in part by dividing the release process as follows: the community maintainer stages the release using sbt-ci-release, then someone from Lightbend has a look and then releases. switching to fully automated publishing is perhaps possible and desirable, but it's another thing to consider. I'm not actually sure if we would need to make some change on the Sonatype end or whether we'd just flip a switch in sbt-ci-release

I have no idea if our account on Sonatype has any storage limits — we'd want to be sure about that before publishing a large number of ephemeral version-tagged releases

so, the status quo remains: if someone wants to test something, they can either `publishLocal` on their own machine, or ask a module maintainer to push a tag
